version: '3'

tasks:

  install:
    desc: Install dependencies
    cmds:
      - poetry install

  check:
    desc: Execute the linter
    cmds:
      - poetry run ruff check

  format:
    desc: Run formater
    cmds:
      - poetry run ruff format
