---
version: '3'

tasks:

  default:
    summary: |
      Just a list of documented tasks.
    silent: true
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - poetry install
      - pipx install -e .

  install:git:
    desc: Install as difftool and diff command for git
    cmds:
      - |
        echo "Pleases see the \"Use as `git-difftool`\" and \"Use as `git diff`\" sections in the README"

  check:
    desc: Execute the linter
    cmds:
      - poetry run ruff check

  format:
    desc: Run formater
    cmds:
      - poetry run ruff format
